<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-12T16:10:47 IST" name="Default suite" finished-at="2024-11-12T16:11:14 IST" duration-ms="26876">
    <groups>
      <group name="smokeTesting">
        <method signature="OrgTest.createOrgWithManadatoryFields()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" name="createOrgWithManadatoryFields" class="com.vtiger.orgtest.OrgTest"/>
      </group> <!-- smokeTesting -->
    </groups>
    <test started-at="2024-11-12T16:10:47 IST" name="Default test" finished-at="2024-11-12T16:11:14 IST" duration-ms="26876">
      <class name="com.vtiger.orgtest.OrgTest">
        <test-method is-config="true" signature="configBS()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:10:43 IST" name="configBS" finished-at="2024-11-12T16:10:47 IST" duration-ms="4539" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configCS()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:10:47 IST" name="configCS" finished-at="2024-11-12T16:10:50 IST" duration-ms="2964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configCS -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:10:50 IST" name="configBM" finished-at="2024-11-12T16:10:55 IST" duration-ms="4601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="createOrgWithManadatoryFields()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:10:55 IST" name="createOrgWithManadatoryFields" finished-at="2024-11-12T16:11:06 IST" duration-ms="11013" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Jelly394] but found [[ ACC151 ] Jelly394 - Organization Information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Jelly394] but found [[ ACC151 ] Jelly394 - Organization Information]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vtiger.crm.generic.ObjectRepositoryUtility.OrganizationDetailsPage.enterDataInOrgField(OrganizationDetailsPage.java:81)
at com.vtiger.orgtest.OrgTest.createOrgWithManadatoryFields(OrgTest.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrgWithManadatoryFields -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:11:06 IST" name="configAM" finished-at="2024-11-12T16:11:14 IST" duration-ms="7527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:11:14 IST" name="configAC" finished-at="2024-11-12T16:11:14 IST" duration-ms="534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:com.vtiger.orgtest.OrgTest@48075da3]" started-at="2024-11-12T16:11:14 IST" name="configAS" finished-at="2024-11-12T16:11:14 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.sql.Connection.close()" because "this.conn" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.close()" because "this.conn" is null
at com.vtiger.crm.generic.databaseutility.DatabaseUtility.closeDbConnection(DatabaseUtility.java:31)
at com.crm.generic.baseutility.BaseClass.configAS(BaseClass.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- com.vtiger.orgtest.OrgTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
